/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NotificationType } from "./types";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NotifyToast {
        /**
          * default: false
         */
        "autoHide": boolean;
        /**
          * default: 3000
         */
        "autoHideAfterMs": number;
        /**
          * The last name
         */
        "headline": string;
        /**
          * default: false
         */
        "isHidden": boolean;
        /**
          * success (default) | info | warning | error
         */
        "type": NotificationType;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNotifyToastElement extends Components.NotifyToast, HTMLStencilElement {
    }
    var HTMLNotifyToastElement: {
        prototype: HTMLNotifyToastElement;
        new (): HTMLNotifyToastElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "notify-toast": HTMLNotifyToastElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NotifyToast {
        /**
          * default: false
         */
        "autoHide"?: boolean;
        /**
          * default: 3000
         */
        "autoHideAfterMs"?: number;
        /**
          * The last name
         */
        "headline"?: string;
        /**
          * default: false
         */
        "isHidden"?: boolean;
        "onToastDismissed"?: (event: CustomEvent<HTMLElement>) => void;
        /**
          * success (default) | info | warning | error
         */
        "type"?: NotificationType;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "notify-toast": NotifyToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "notify-toast": LocalJSX.NotifyToast & JSXBase.HTMLAttributes<HTMLNotifyToastElement>;
        }
    }
}
